### ISSUE TITLE
No ability to remove a field by update

### ISSUE THREAD

**Issue by akolotov** [citrusvanilla/tinyflux#27]
Since `update` is used to modify an point's fileds dict, new fileds will be added and existing fields will not be deleted.

https://github.com/citrusvanilla/tinyflux/blob/24ab88df321038a0eb664f3b6a254df6d5a3f2e5/tinyflux/database.py#L1223

Let me explain it by the code:
```
>>> tags = TagQuery()
>>> q = tags.id == "some-unique-value"
>>> db.get(q)
Point(time=2023-02-01T19:26:28+00:00, measurement=_default, tags=id:some-unique-value, fields=sensor1:58)
... def generalize_sensors(fields):
...     if "sensor1" in fields:
...         return {"sensor": fields["sensor1"]}
...     else:
...         return fields
>>> db.update(q, fields=generalize_sensors)
>>> db.get(q)
Point(time=2023-02-01T19:26:28+00:00, measurement=_default, tags=id:some-unique-value, fields=sensor1:58; sensor:58)
```
I would expect that `generalize_sensors` will remove `sensor1` from the fields since it does not use `**fields` in the returning dict.

**Comment by citrusvanilla** [comment]
Thanks for this issue.  I too originally wondered why an `update` operation should not completely overwrite a field set or tag set when I wrote this code.  The behavior of `update` mirrors however was ultimately chosen to match that of [Python's `dict` `update` method](https://docs.python.org/3/library/stdtypes.html#dict.update), which is to overwrite the specified _key/values_ only, and _not_ to overwrite the whole object (and in potentially doing so,  delete unspecified keys):

```python
>>> d = {"a": 1}
>>> d.update({"b": 2})
>>> d
{'a': 1, 'b': 2}
```

Both the FieldSet and TagSet are Python `dict`s so `update` on them will behave the same way.

In trying to understand your issue, I actually found a bug in the latest release, see issue #28 .  It has been addressed and fixed in v0.2.4 so if you were getting a `TypeError: 'Point' object is not subscriptable` exception when updating with CSVStorage, this has been fixed.

Currently TinyFlux does not have a way to delete existing field keys or tag keys.  I agree this could be a useful feature.  I will put it in the roadmap.  It should work like:

```python
from tinyflux.operations import delete_key
q = FieldQuery().my_field == "sensor1"
db.update_all(q, delete_key("sensor"))
```

**Comment by akolotov** [comment]
@citrusvanilla thanks for detailed explanation. Let me explain why I expected another behaviour for the update operation.
There is an example on [the corresponding page of the documentation](https://tinyflux.readthedocs.io/en/latest/updating-data.html):
```
def fahrenheit_to_celcius(fields):
    if "temp" in fields:
        temp_f = fields["temp"]
        temp_c =  (temp_f - 32.0) * (5/9)
        return {**fields, "temp": temp_c}
    else:
        return fields
db.update_all(fields=fahrenheit_to_celcius)
```
Where `**fields` assumes that existing fields of the point will be returned after transformation `fahrenheit_to_celcius`.

So, it looks logical that if the previous point fields are no needed, `**fields` could be omitted. But it is not true -- both`return {**fields, "temp": temp_c}` and `return {"temp": temp_c}` will behave in the same way.

**Comment by citrusvanilla** [comment]
Thanks, I've update the [documentation](https://tinyflux.readthedocs.io/en/latest/updating-data.html) to state that tag and field keys can only be overwritten, and not deleted, using the `.update()` method.  I am working on supporting deleteing key and tags in a different branch.

**Comment by citrusvanilla** [comment]
Removal of individual tags and keys is now supported in version 0.4.  Read the documentation for informaiton: https://tinyflux.readthedocs.io/en/latest/removing-data.html#removing-tags-and-fields

**Comment by akolotov** [comment]
You rock! Thanks!
