### ISSUE TITLE
Retrieving Points with the max timestamp from the db

### ISSUE THREAD

**Issue by noeldum** [citrusvanilla/tinyflux#44]
**Is your feature request related to a problem? Please describe.**
I am trying to get the very last entry inserted in the database. From the doc I can't see any way to do this efficiently.
I was hoping to be able to query by index but this is not an option.

**Describe the solution you'd like**
Ideally a db.last() function to return the last inserted point would work well.
If not I would be happy to know any efficient way to get the last entry of the db.

**Describe alternatives you've considered**
Well I could maybe query by time with a start time early enough to grab at least one point. 
Then collect the last entry in the list. Not great.

**Additional context**
nothing to add

**Comment by noeldum** [comment]
I found one way to do it with the index.latest_time function (which is with a tipo as lates**e**t_time, I must have an older version)
```
Time = TimeQuery()
t = db.index.lateset_time
db.search(Time == t1)
```
Let me know if there is a better way to it.

It could be nice to include the usage of latest_time in the doc.

**Comment by citrusvanilla** [comment]
The current index in tinyflux does not keep track of the order of what was recently inserted into the database.  Even if this was supported, the index would be wiped of this information when the python process is stopped since the index is not persistent (like you will find in a db server).

Are you trying to get the latest timestamp associated with a Point?  I suppose there is a case where you insert a Point that is way into the past when you manually specify the time to be in the past- do you want to retrieve this item?  Or simply the item with the most-recent timestamp?  To get the Point with the latest timestamp:

There is an API call for the Index actually that is used internally, if you want to access it directly as sort-of a hack, do this:

```python
from tinyflux import TinyFlux, Point

# Your db.
db = TinyFlux("test.db")

# Make sure the index is valid.  It should be unless you turned indexing off yourself.
assert db.index._valid

# Here's the api call:
max_time = db.index.latest_time

print(max_time)
```

should print `2023-09-25 20:18:57.502769+00:00`

I just saw your follow up and fixed the spelling bug.  There is a new version, 0.4.1, with the spelling fixed.  Here is the reference in the readme:

https://tinyflux.readthedocs.io/en/latest/tinyflux.html#tinyflux.index.Index.latest_time

**Comment by noeldum** [comment]
Thank you. Yes it's the latest timestamp that I need. Not the latest inserted although in my particular application they are always the same. A plain write once recording db.

will go with the latest_time method then.
